import React, { useState } from "react";
import { AuthSession } from "../types";
import { SionDatabase } from "../utils/db";

export default function ActivationScreen({ onAuthenticated }: { onAuthenticated: (session: AuthSession) => void }) {
  const token = new URLSearchParams(window.location.search).get("token") || "";
  const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); if (!token) return setError("Tautan aktivasi tidak lengkap."); if (password.length < 12) return setError("Password minimal 12 karakter."); if (password !== confirm) return setError("Konfirmasi password belum sama."); setBusy(true); try { onAuthenticated(await SionDatabase.activate(token, password)); window.history.replaceState(null, "", "/dashboard"); } catch (err: any) { setError(err.message || "Aktivasi gagal."); } finally { setBusy(false); } };
  return <main className="grid min-h-screen place-items-center bg-slate-100 p-4"><form onSubmit={submit} className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-8 shadow-xl"><h1 className="text-2xl font-bold">Aktifkan Akun</h1><p className="mt-2 text-sm text-slate-500">Buat password baru untuk menyelesaikan aktivasi akun Anda.</p><label className="mt-6 block text-sm font-bold">Password baru<input value={password} onChange={(e) => setPassword(e.target.value)} type="password" minLength={12} required autoComplete="new-password" className="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3" /></label><label className="mt-4 block text-sm font-bold">Konfirmasi password<input value={confirm} onChange={(e) => setConfirm(e.target.value)} type="password" minLength={12} required autoComplete="new-password" className="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3" /></label>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="mt-6 w-full rounded-xl bg-red-600 py-3 text-sm font-bold text-white disabled:bg-slate-400">{busy ? "Mengaktifkan..." : "Aktifkan akun"}</button></form></main>;
}
